# Generated by Django 3.2.10 on 2022-01-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='r_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
