# Generated by Django 3.2.10 on 2022-01-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
    ]
